version: '3.8'
services:
  slave0:
    image: alpine:latest
    command: sleep infinity
    networks:
      - slave
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  slave:
    ipam:
      config:
        - subnet: 172.56.20.16/28
          gateway: 172.56.20.17